### ISSUE TITLE
Fix script for Blue ships and weapon resources

### ISSUE THREAD

**Issue by Pixel-Skull** [Quinnsicle/arcs_tts#17]
It is necessary to replace 
1) all word "Weapons" with "Weapon" case sensitive.
2) also replace "Blue" with "Teal" case sensitive.

**Comment by Pixel-Skull** [comment]
Additionaly i found that 
1) "Imperial Ship (Fresh)" -> "Imperial Ship" (dont know why, but it has script if damaged, and with this fix work for every state)
2) "BLue Ship" -> "Teal ship" (found that when try to return damaged teal ship)

**Comment by Pixel-Skull** [comment]
[3037846252.json](https://github.com/user-attachments/files/16984768/3037846252.json)
attach the fixed json file

**Comment by Quinnsicle** [comment]
This commit should fix it. 
https://github.com/Quinnsicle/arcs_tts/commit/7c7323e9b62f671e52bc7f67a2e20bfcce8d1556
