### ISSUE TITLE
Issue with automated setup for 3 players.

### ISSUE THREAD

**Issue by Laurens1234** [Quinnsicle/arcs_tts#18]
When setting up a 3 player game the 2nd and 3rd players starting location are different from what's on the setup card (they're swapped).

**Comment by Laurens1234** [comment]
Some 4 players game setup scripts are also incorrect.

**Comment by Quinnsicle** [comment]
Do you know which setup cards are incorrect?

**Comment by Laurens1234** [comment]
I could name some specifically (for example: 3 player - frontiers, l&l turned on, blue has initiave, yellow and white are swapped) but it's hard to give a comprehensive list because the same ones are not always incorrect. I think there might be some factor like which player colors are in the game or who start with the inititiave that changes things. I can tell you that in my experience with 3 player games player 1 has never been wrong and player 2 and 3 are often swapped. Player 1 in 4 player has also always been correct but I haven't played many 4 player games.

**Comment by fallspectrum** [comment]
@Quinnsicle I also encountered bug during 4 player setup.  White had initiative (player 1) during leaders setup, 4 Players - Mix Up 1 was the map format. Yellow + Teal/Blue's starting positions were swapped. 

Player 2 and player 3 had to swap their locations to fix: (2a <-> 3a, 2b <-> 3b, 2c <-> 3c)

**Comment by Quinnsicle** [comment]
Thank you @fallspectrum for the fix!
