### ISSUE TITLE
function <end_round>: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by fallspectrum** [Quinnsicle/arcs_tts#20]
After clicking End Round, this error is emitted.

While inspectiing end_round(),  tracing: https://github.com/Quinnsicle/arcs_tts/blob/main/src/Control.lua#L131 it seems AmbitionMarkers.reset_zero_marker() does not fully complete.

After commenting AmbitionMarkers.display_declare_button() here: https://github.com/Quinnsicle/arcs_tts/blob/main/src/AmbitionMarkers.lua#L158

AmbitionMarkers.reset_zero_marker() now completes and end_round() can make further progress. 

I'm not sure what the intention of displaying the ambition declare button is during reset_zero_marker(), feels unintentional, maybe should be removed or handled elsewhere.

**Comment by Quinnsicle** [comment]
We had a feature that automated declaring but I found some bugs when refactoring and decided to disable it for now.
