### ISSUE TITLE
Enhancement: Camera Controls

### ISSUE THREAD

**Issue by fallspectrum** [Quinnsicle/arcs_tts#40]
Looking at the Gloomhaven TTS mod, I like the camera controls provided in the top right corner.  Would be nice to replicate similar UI in a nearby area.

For Arcs I could see the usefulness of camera jump points for:
- High-level top view of full board + player boards (already a default for whomever clips End Round)
- Zoomed in view of the game board (not including each player board)
- Dice Board
- A jump button for each active player board

![camera_controls](https://github.com/user-attachments/assets/c8e8d1ff-bc7c-49af-b39d-0445bd5ccaa2)
 the camera control

**Comment by fallspectrum** [comment]
#43 has some working implementation so far, but I'm undecided on if it's valuable enough to put in yet, would like to playtest it more.

**Comment by fallspectrum** [comment]
#52

**Comment by Quinnsicle** [comment]
https://github.com/Quinnsicle/arcs_tts/pull/65
