### ISSUE TITLE
Tag campaign cards

### ISSUE THREAD

**Issue by Quinnsicle** [Quinnsicle/arcs_tts#47]
Banished Nov 1 @ 6:11pm 
In campaign setup, the Lore cards and the court deck cannot be shuffled together because the decks have different component tags. The lore deck has the "Lore" tag and the court deck has the "Campaign Only" and "Guild" tags. Until this is fixed in scripting, the tags have to be added manually to the Lore deck (tags can be edited by right clicking on a deck).

Banished Nov 2 @ 10:38pm 
Another thing to fix : Many cards in the fate sets must be later added to the court deck and/or the action cards deck. They require the "Guild" and "Action" tags respectively.

Also the back of flagship boards have the wrong image link now.

**Comment by fallspectrum** [comment]
> In campaign setup, the Lore cards and the court deck cannot be shuffled together because the decks have different component tags. The lore deck has the "Lore" tag and the court deck has the "Campaign Only" and "Guild" tags. Until this is fixed in scripting, the tags have to be added manually to the Lore deck (tags can be edited by right clicking on a deck).

This should already be addressed by #38 

> Another thing to fix : Many cards in the fate sets must be later added to the court deck and/or the action cards deck. They require the "Guild" and "Action" tags respectively.

This requires attention

**Comment by fallspectrum** [comment]
@Quinnsicle I started on some tagging efforts.  https://github.com/fallspectrum/arcs_tts/pull/5/files (this PR is only against my fork so I can track overall changes/progress)

I've yet to go through fate bags as I have some questions... I suspect we should come to a consensus on a naming/tagging schema as I see some inconsistencies in naming of Court cards, action cards, etc...

The "bottom of card" description (Lore, Vox, Guild, Title, Resolution, Law, Edict, Setup, etc), these can easily all be tags.

How Name, Nickname, and Description should be used is more of what needs clarification.

Silver Tongues as a Guild card has "Psionic" as a Description, and that is used for counting resources on the playerboard.  Similarly Psionic tokens have "Psionic" in their description.  While using tags to count resources IMO is more flexible, that is how they're being used currently so I'm planning to leave Descriptions alone and only worry about Tags and filling in Nicknames for each card as I go.  Let me know if that's appropriate.

**Comment by fallspectrum** [comment]
Would probably also help keep items organized if we added a F# tag for all items associated with that fate.  F1, F2, F3, etc.

**Comment by Quinnsicle** [comment]
Yes I think this all sound good. I can't remember why we went away from using tags. It was causing some issues with another contributor and so we set that standard going forward. I'd prefer to use tags though.
